import React from 'react';

export const FeatureList: React.FC = () => {
    return (
        <section className="mt-12 w-full max-w-3xl mx-auto text-left">
            <h2 className="text-2xl font-bold text-center text-transparent bg-clip-text bg-gradient-to-r from-teal-300 to-cyan-400 mb-6">
                Key Features
            </h2>
            <div className="space-y-4 text-gray-300 bg-gray-800/40 p-6 rounded-lg ring-1 ring-white/10">
                <div className="p-4 rounded-md bg-gray-900/50">
                    <h3 className="font-semibold text-teal-400">Audio File Upload</h3>
                    <p className="text-sm mt-1">
                        Easily upload your audio files by dragging and dropping or clicking to select a file.
                    </p>
                </div>
                <div className="p-4 rounded-md bg-gray-900/50">
                    <h3 className="font-semibold text-teal-400">Smart Transcription & Synchronization</h3>
                    <p className="text-sm mt-1">
                        The full text of your audio is transcribed using Gemini AI, with precise word timings for synchronized highlighting as the audio plays.
                    </p>
                </div>
                <div className="p-4 rounded-md bg-gray-900/50">
                    <h3 className="font-semibold text-teal-400">Music Chord Detection</h3>
                    <p className="text-sm mt-1">
                        If your audio file contains music, its chords are automatically detected and displayed in a separate section.
                    </p>
                </div>
                <div className="p-4 rounded-md bg-gray-900/50">
                    <h3 className="font-semibold text-teal-400">Professional PowerPoint Export</h3>
                    <ul className="list-disc list-inside text-sm mt-2 space-y-1 pl-2">
                        <li><span className="font-medium">Smart Slides:</span> Your text is intelligently divided into short, readable slides.</li>
                        <li><span className="font-medium">Image Generation per Slide:</span> A unique and relevant background image is generated by AI for each slide.</li>
                        <li><span className="font-medium">Embedded Audio:</span> Your original audio file is embedded in the first slide to play along with the presentation.</li>
                        <li><span className="font-medium">Show-Ready Format:</span> The final file is saved as a <code className="bg-gray-700 px-1 rounded">.ppsx</code>, which opens directly in presentation mode and includes a non-editable tag.</li>
                    </ul>
                </div>
                 <div className="p-4 rounded-md bg-gray-900/50">
                    <h3 className="font-semibold text-teal-400">Download Transcript</h3>
                    <p className="text-sm mt-1">
                        Download the complete transcript as a text file (<code className="bg-gray-700 px-1 rounded">.txt</code>) with a single click.
                    </p>
                </div>
            </div>
        </section>
    );
};
